// This file is generated by scripts/generate-content.js. Edit content/tools/*.md instead.
export const toolsData = [
  {
    "id": "vscode",
    "name": "VS Code",
    "icon": "💻",
    "description": "轻量但强大的代码编辑器，适合前端、后端、数据分析和远程开发。",
    "category": "开发工具",
    "tags": [
      "编辑器",
      "开源",
      "跨平台"
    ],
    "detailUrl": "tool-detail.html?id=vscode",
    "color": "#007ACC",
    "homepage": "https://code.visualstudio.com/",
    "order": 10
  },
  {
    "id": "figma",
    "name": "Figma",
    "icon": "🎨",
    "description": "基于浏览器的协作式界面设计工具，适合 UI、原型和设计系统。",
    "category": "设计工具",
    "tags": [
      "设计",
      "协作",
      "云端"
    ],
    "detailUrl": "tool-detail.html?id=figma",
    "color": "#F24E1E",
    "homepage": "https://www.figma.com/",
    "order": 20
  },
  {
    "id": "notion",
    "name": "Notion",
    "icon": "📝",
    "description": "集笔记、文档、任务和知识库于一体的生产力工具。",
    "category": "效率工具",
    "tags": [
      "笔记",
      "知识库",
      "任务管理"
    ],
    "detailUrl": "tool-detail.html?id=notion",
    "color": "#111111",
    "homepage": "https://www.notion.so/",
    "order": 30
  },
  {
    "id": "raycast",
    "name": "Raycast",
    "icon": "⚡",
    "description": "macOS 上的启动器和效率工具，可以快速执行常用操作。",
    "category": "效率工具",
    "tags": [
      "启动器",
      "Mac",
      "效率"
    ],
    "detailUrl": "tool-detail.html?id=raycast",
    "color": "#FF6363",
    "homepage": "https://www.raycast.com/",
    "order": 40
  },
  {
    "id": "github",
    "name": "GitHub",
    "icon": "◇",
    "description": "代码托管和协作平台，适合开源项目、个人网站和自动化部署。",
    "category": "开发工具",
    "tags": [
      "代码托管",
      "开源",
      "部署"
    ],
    "detailUrl": "tool-detail.html?id=github",
    "color": "#24292E",
    "homepage": "https://github.com/",
    "order": 50
  },
  {
    "id": "obsidian",
    "name": "Obsidian",
    "icon": "◆",
    "description": "基于本地 Markdown 文件的知识管理工具，强调数据所有权和双向链接。",
    "category": "效率工具",
    "tags": [
      "Markdown",
      "本地优先",
      "知识管理"
    ],
    "detailUrl": "tool-detail.html?id=obsidian",
    "color": "#7C3AED",
    "homepage": "https://obsidian.md/",
    "order": 60
  }
]

export const toolDetails = {
  "figma": {
    "title": "Figma 设计指南",
    "name": "Figma",
    "category": "设计工具",
    "tags": [
      "设计",
      "协作",
      "云端"
    ],
    "description": "基于浏览器的协作式界面设计工具，适合 UI、原型和设计系统。",
    "homepage": "https://www.figma.com/",
    "content": "<p>Figma 已经成为 UI/UX 设计里非常常见的工具。它最重要的价值不是“能画图”，而是让设计、产品、开发能在同一个文件里对齐。</p>\n<h2>核心优势</h2>\n<ul>\n<li>实时协作，适合团队一起看稿和改稿</li>\n<li>Auto Layout 可以更接近真实前端布局</li>\n<li>Components 和 Variants 适合沉淀设计系统</li>\n</ul>\n<h2>推荐用法</h2>\n<p>把常用组件先做成规范，再开始堆页面。这样后面改按钮、颜色、间距时，维护成本会低很多。</p>"
  },
  "github": {
    "title": "GitHub 使用技巧",
    "name": "GitHub",
    "category": "开发工具",
    "tags": [
      "代码托管",
      "开源",
      "部署"
    ],
    "description": "代码托管和协作平台，适合开源项目、个人网站和自动化部署。",
    "homepage": "https://github.com/",
    "content": "<p>GitHub 不只是放代码的地方。对于个人网站来说，它还可以负责版本管理、协作修改和自动部署。</p>\n<h2>实用功能</h2>\n<ul>\n<li>Pull Request：在发布前检查改动</li>\n<li>Actions：自动构建和部署</li>\n<li>Pages：免费托管静态网站</li>\n<li>Issues：记录后续想做的功能</li>\n</ul>\n<h2>适合个人项目的用法</h2>\n<p>用 GitHub 管理个人网站、知识库或作品集很方便。它能记录每次修改，也能让你在发布前清楚看到变更。</p>"
  },
  "notion": {
    "title": "Notion 知识库搭建",
    "name": "Notion",
    "category": "效率工具",
    "tags": [
      "笔记",
      "知识库",
      "任务管理"
    ],
    "description": "集笔记、文档、任务和知识库于一体的生产力工具。",
    "homepage": "https://www.notion.so/",
    "content": "<p>Notion 的优势是灵活：同一套页面可以是笔记、数据库、项目看板，也可以是公开文档。</p>\n<h2>我会怎么组织</h2>\n<ul>\n<li>每日日志：记录工作和想法</li>\n<li>项目管理：维护正在推进的事情</li>\n<li>读书笔记：沉淀长期有用的内容</li>\n<li>工具收藏：记录软件、网站和配置心得</li>\n</ul>\n<h2>注意点</h2>\n<p>不要一开始就做太复杂的系统。先用起来，再根据真实需求慢慢调整结构。</p>"
  },
  "obsidian": {
    "title": "Obsidian 笔记法",
    "name": "Obsidian",
    "category": "效率工具",
    "tags": [
      "Markdown",
      "本地优先",
      "知识管理"
    ],
    "description": "基于本地 Markdown 文件的知识管理工具，强调数据所有权和双向链接。",
    "homepage": "https://obsidian.md/",
    "content": "<p>Obsidian 的核心优势是本地优先。你的笔记就是普通 Markdown 文件，不容易被某个平台锁住。</p>\n<h2>核心概念</h2>\n<ul>\n<li>双向链接：让笔记之间形成网络</li>\n<li>图谱视图：观察知识连接</li>\n<li>插件生态：补足日历、查询、模板等能力</li>\n</ul>\n<h2>适合什么场景</h2>\n<p>适合长期沉淀笔记、项目资料和个人知识库。越是想保留原始文件所有权，越能感受到它的价值。</p>"
  },
  "raycast": {
    "title": "Raycast 效率指南",
    "name": "Raycast",
    "category": "效率工具",
    "tags": [
      "启动器",
      "Mac",
      "效率"
    ],
    "description": "macOS 上的启动器和效率工具，可以快速执行常用操作。",
    "homepage": "https://www.raycast.com/",
    "content": "<p>Raycast 适合希望减少鼠标操作的人。它把应用启动、剪贴板、窗口管理、扩展命令放在同一个入口。</p>\n<h2>常用功能</h2>\n<ul>\n<li>快速启动应用</li>\n<li>搜索剪贴板历史</li>\n<li>管理窗口位置</li>\n<li>通过扩展连接 GitHub、Linear、Notion 等工具</li>\n</ul>\n<h2>使用建议</h2>\n<p>先从启动应用和剪贴板历史开始。等形成肌肉记忆后，再逐步加入扩展。</p>"
  },
  "vscode": {
    "title": "VS Code 使用心得",
    "name": "VS Code",
    "category": "开发工具",
    "tags": [
      "编辑器",
      "开源",
      "跨平台"
    ],
    "description": "轻量但强大的代码编辑器，适合前端、后端、数据分析和远程开发。",
    "homepage": "https://code.visualstudio.com/",
    "content": "<p>Visual Studio Code 是我日常开发中使用频率最高的工具。它轻量、快速，同时拥有成熟的插件生态。</p>\n<h2>适合谁</h2>\n<ul>\n<li>需要一个启动快、扩展多的代码编辑器</li>\n<li>经常在不同语言和项目之间切换</li>\n<li>希望把 Git、终端、调试都放在一个工作界面里</li>\n</ul>\n<h2>常用插件</h2>\n<ul>\n<li><code>ESLint</code>：JavaScript / TypeScript 代码检查</li>\n<li><code>Prettier</code>：统一代码格式</li>\n<li><code>GitLens</code>：增强 Git 历史和 blame 信息</li>\n</ul>\n<h2>小建议</h2>\n<p>先掌握命令面板和快速打开文件，再慢慢补插件。编辑器越轻，工作流越顺。</p>"
  }
}

export const categories = [
  "全部",
  "开发工具",
  "设计工具",
  "效率工具"
]
